apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/client-version: 565.0.0
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/maxScale: '20'
    run.googleapis.com/operation-id: 30ce0ce3-0797-4319-81d1-1994055509fb
    run.googleapis.com/urls: '["https://amjis-sidecar-938361928218.asia-south1.run.app","https://amjis-sidecar-qm256lasva-el.a.run.app"]'
    serving.knative.dev/creator: mail.abhisek.mohanty@gmail.com
    serving.knative.dev/lastModifier: mail.abhisek.mohanty@gmail.com
  creationTimestamp: '2026-04-25T15:59:38.352610Z'
  generation: 1
  labels:
    cloud.googleapis.com/location: asia-south1
    run.googleapis.com/satisfiesPzs: 'true'
  name: amjis-sidecar
  namespace: '938361928218'
  resourceVersion: AAZQSvoUTM0
  selfLink: /apis/serving.knative.dev/v1/namespaces/938361928218/services/amjis-sidecar
  uid: f0670ee3-573a-4629-bd88-e121246b2e4b
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 565.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: hknvjdripq
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: SIDECAR_API_KEY
          value: local-dev
        image: asia-south1-docker.pkg.dev/madhav-astrology/amjis/amjis-sidecar:latest
        ports:
        - containerPort: 8000
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8000
          timeoutSeconds: 240
      serviceAccountName: 938361928218-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: https://amjis-sidecar-qm256lasva-el.a.run.app
  conditions:
  - lastTransitionTime: '2026-04-25T16:00:13.700301Z'
    status: 'True'
    type: Ready
  - lastTransitionTime: '2026-04-25T16:00:08.141927Z'
    status: 'True'
    type: ConfigurationsReady
  - lastTransitionTime: '2026-04-25T16:00:13.671207Z'
    status: 'True'
    type: RoutesReady
  latestCreatedRevisionName: amjis-sidecar-00001-s55
  latestReadyRevisionName: amjis-sidecar-00001-s55
  observedGeneration: 1
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: amjis-sidecar-00001-s55
  url: https://amjis-sidecar-qm256lasva-el.a.run.app
