steps:
  - id: build-pipeline-image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - platform/python-sidecar/Dockerfile.pipeline
      - -t
      - asia-south1-docker.pkg.dev/$PROJECT_ID/marsys-pipeline/pipeline:$BUILD_ID
      - -t
      - asia-south1-docker.pkg.dev/$PROJECT_ID/marsys-pipeline/pipeline:latest
      - --build-arg
      - PIPELINE_VERSION=$BUILD_ID
      - .

  - id: push-image
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - --all-tags
      - asia-south1-docker.pkg.dev/$PROJECT_ID/marsys-pipeline/pipeline

  - id: deploy-job
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - jobs
      - update
      - marsys-build-pipeline-job
      - --image=asia-south1-docker.pkg.dev/$PROJECT_ID/marsys-pipeline/pipeline:$BUILD_ID
      - --region=asia-south1

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - asia-south1-docker.pkg.dev/$PROJECT_ID/marsys-pipeline/pipeline:$BUILD_ID
  - asia-south1-docker.pkg.dev/$PROJECT_ID/marsys-pipeline/pipeline:latest
