export type FeatureFlag =
  | 'PANEL_MODE_ENABLED'
  | 'MANIFEST_BUILDER_ENABLED'
  | 'LLM_CHECKPOINTS_ENABLED'
  | 'BUNDLE_AUGMENTER_ENABLED'
  | 'MSR_RERANKER_ENABLED'
  | 'SEMANTIC_GATE_ENABLED'
  | 'NEW_QUERY_PIPELINE_ENABLED'
  | 'VALIDATOR_FAILURE_HALT'
  | 'SYNTHESIS_PROMPT_DEBUG'
  | 'DISCLOSURE_TIER_DEBUG'
  | 'AUDIT_ENABLED'
  | 'AUDIT_VIEW_VISIBLE'
  | 'PANEL_CHECKBOX_VISIBLE'
  | 'BUNDLE_COMPOSER_DEBUG'
  | 'CGM_GRAPH_WALK_ENABLED'
  | 'MANIFEST_QUERY_ENABLED'
  | 'VECTOR_SEARCH_ENABLED'
  // Phase 6 — LLM Checkpoints (all default OFF; flip individually after warn-mode observation)
  | 'CHECKPOINT_4_5_ENABLED'
  | 'CHECKPOINT_4_5_FAIL_HARD'
  | 'CHECKPOINT_5_5_ENABLED'
  | 'CHECKPOINT_5_5_FAIL_HARD'
  | 'CHECKPOINT_8_5_ENABLED'
  | 'CHECKPOINT_8_5_FAIL_HARD'
  | 'CHECKPOINT_8_5_PREDICTION_EXTRACT'
  // Phase 7 — Panel Mode
  | 'PANEL_DEGRADE_2_OF_3'
  // Portal Redesign
  | 'PORTAL_REDESIGN_R0_ENABLED'
  | 'PORTAL_REDESIGN_R5_ENABLED'

export const DEFAULT_FLAGS: Record<FeatureFlag, boolean> = {
  PANEL_MODE_ENABLED: true,
  MANIFEST_BUILDER_ENABLED: false,
  LLM_CHECKPOINTS_ENABLED: false,
  BUNDLE_AUGMENTER_ENABLED: false,
  MSR_RERANKER_ENABLED: false,
  SEMANTIC_GATE_ENABLED: false,
  NEW_QUERY_PIPELINE_ENABLED: true,
  VALIDATOR_FAILURE_HALT: true,
  SYNTHESIS_PROMPT_DEBUG: false,
  DISCLOSURE_TIER_DEBUG: false,
  AUDIT_ENABLED: true,
  AUDIT_VIEW_VISIBLE: false,
  PANEL_CHECKBOX_VISIBLE: false,
  BUNDLE_COMPOSER_DEBUG: false,
  CGM_GRAPH_WALK_ENABLED: true,
  MANIFEST_QUERY_ENABLED: true,
  VECTOR_SEARCH_ENABLED: true,
  CHECKPOINT_4_5_ENABLED: false,
  CHECKPOINT_4_5_FAIL_HARD: false,
  CHECKPOINT_5_5_ENABLED: false,
  CHECKPOINT_5_5_FAIL_HARD: false,
  CHECKPOINT_8_5_ENABLED: false,
  CHECKPOINT_8_5_FAIL_HARD: false,
  CHECKPOINT_8_5_PREDICTION_EXTRACT: false,
  // Phase 7 — Panel Mode (all default OFF)
  PANEL_DEGRADE_2_OF_3: false,
  // Portal Redesign (default ON)
  PORTAL_REDESIGN_R0_ENABLED: true,
  PORTAL_REDESIGN_R5_ENABLED: true,
}

// Numeric config keys (read via configService.getValue)
export const CGM_GRAPH_WALK_MAX_DEPTH_KEY = 'CGM_GRAPH_WALK_MAX_DEPTH'
export const VECTOR_SEARCH_TOP_K_KEY = 'VECTOR_SEARCH_TOP_K'
export const CGM_GRAPH_WALK_MAX_DEPTH_DEFAULT = 3
export const VECTOR_SEARCH_TOP_K_DEFAULT = 20

export const FLAG_ENV_PREFIX = 'MARSYS_FLAG_'
