-- Run after creating the astrologer user account via Supabase Auth dashboard.
-- Replace the UUID with the actual auth.users.id of the astrologer account.
-- This is a one-time seed — the trigger handles future signups automatically.

-- First: sign up via the app with ASTROLOGER_EMAIL, then get the user ID from
-- Supabase dashboard → Authentication → Users, and run:
--
-- update public.profiles set role = 'astrologer' where id = '<user-uuid>';
--
-- The handle_new_user trigger checks app.astrologer_email for future signups,
-- but the very first signup happens before this setting is configured, so
-- a manual update is needed once.
